### ISSUE TITLE
My test keeps crashing `EXC_BAD_ACCESS`

### ISSUE THREAD

**Issue by Boowman** [Kolos65/Mockable#16]
```swift
import Foundation
import Mockable

@Mockable
protocol TestProtocol {
    func testing(val: String) -> String
}

class TestService: TestProtocol {
    func testing(val: String = "") -> String {
        return "Testing"
    }
}


class TestViewModel: ObservableObject {
    private var services: TestProtocol
    private var value: String = ""
    
    init() {
        services = TestService()
        value = services.testing(val: "Some cool")
    }
    
    convenience init(services: TestProtocol) {
        self.init()
        self.services = services
        self.value = services.testing(val: "Whyyy")
    }
    
    func getValue() -> String {
        return value
    }
}
```
I have imported `MockableTest` into my test file, I have added `MOCKING` under Custom Flags for Debug and I added Mockable into my main target.

<img width="1063" alt="Screenshot 2024-02-05 at 09 44 30" src="https://github.com/Kolos65/Mockable/assets/3323440/5ac7c313-5772-4d9c-9a95-f9b28b0227db">

**Comment by Kolos65** [comment]
I cant reproduce this, your example is working fine on my end... Can you share your full test case? Do you always get BAD_ACCESS or just every other run?

**Comment by Boowman** [comment]
I get it every run, I tried it in a blank project same issue.
<img width="936" alt="Screenshot 2024-02-05 at 10 25 53" src="https://github.com/Kolos65/Mockable/assets/3323440/9ac6050a-e92e-4fe6-95a4-78992ee95f32">
<img width="936" alt="Screenshot 2024-02-05 at 10 26 05" src="https://github.com/Kolos65/Mockable/assets/3323440/323942ac-b58c-4ae4-95b0-b760e01dd6ab">

**Comment by Kolos65** [comment]
Please send me a link to an example project, I still cannot repro this. What version of Xcode are you using?

**Comment by Kolos65** [comment]
I found it: 

Under the **General** settings of your **PlayWorldTests** target, go to **Frameworks and Libraries** and remove **Mockable** (keeping **MockableTest**).

**MockableTest** also includes **Mockable** so you only need to add **MockableTest** to your test targets. See the [docs](https://kolos65.github.io/Mockable/documentation/mockable/installation/) for more info.

**Comment by Boowman** [comment]
Well, I have good news and bad news: 

- Good news is that you are right Mockable shouldn't have been added to the test target, not sure how it got there. Once I removed it it worked.
- Bad news is that I checked my main project and it still fails, double double-checked to make sure the package is only added where it should be. I know there's not much more you can do since I can't send over this one but I will keep looking and update this issue with what I find.

**Comment by Kolos65** [comment]
clean + reset packages cache + delete derived data + reopen xcode

**Comment by Boowman** [comment]
That did not seem to work, I am wondering if there is something I have to have enabled. I remember in other new projects I would get a popup on the side to allow macros. I didn't get it this time as it was an older project.
