### ISSUE TITLE
Namespacing Scope enumeration

### ISSUE THREAD

**Issue by EnesKaraosman** [Kolos65/Mockable#19]
The enum name `Scope` may conflict with other packages. So can we put `Scope` into a namespace? Maybe inside a proper class/enum?

Ex: Personally I'm using `Factory` package which has `Scope` as well. So it's conflicting.

**Comment by Kolos65** [comment]
Thanks for the issue @EnesKaraosman 🙏 
Renamed `Scope` to `MockerScope` in #20.
Will merge it soon and release a new version.
