### ISSUE TITLE
Protocol inheritance and composition

### ISSUE THREAD

**Issue by VisualDeceit** [Kolos65/Mockable#24]
Hello. 
Is there a way to mocking protocols  that combine multiple protocols? 
I try some like this, but got the error. 
```
protocol ServiceA {
    func fooA()
}

protocol ServiceB {
    func fooB()
}

@Mockable
protocol SummaryService: ServiceA, ServiceB {}
```
`Type 'MockSummaryService' does not conform to protocol 'ServiceA'`
`Type 'MockSummaryService' does not conform to protocol 'ServiceB'`

**Comment by Kolos65** [comment]
Hey @VisualDeceit!

Unfortunately protocol inheritance is not supported. This limitation stems from the nature of peer macros: you simply have no access to any information about the protocols you inherit from so there is no way of conforming to them automatically.

**Comment by Kolos65** [comment]
I know its not ideal, but you can conform to the inherited protocols in an extension and still use the generated mock implementation for testing:

```swift
extension Mock SummaryService {
    func fooA() {}
    func fooB() {}
}
```
