### ISSUE TITLE
Void method shouldn't need explicit given clause.

### ISSUE THREAD

**Issue by hainayanda** [Kolos65/Mockable#33]
So I have this kind of routing protocol:

```swift
protocol MyViewRouting {
    func routeToSomeView()
}
```

I just want to verify that ViewModel is calling `routeToSomeView()` method once but it will throw a fatal error unless I do something like this which feels unnecessary since it's a non-throwing void method after all:

```swift
given(router) .routeToHome().willReturn()
```

I think in this scenario, this given shouldn't be required at all.

**Comment by Kolos65** [comment]
See #28 ans #25
