### ISSUE TITLE
Evolution to solve the protocol inheritance generation

### ISSUE THREAD

**Issue by ArseneSoulie** [Kolos65/Mockable#61]
I would like to have your thoughts on a potential evolution to make protocol inheritance possible with swift macros for mock generation. This is intended as a discussion topic rather than a formal issue.

Let's say that I have the following protocols
```swift
protocol Drivable {
    func drive()
}

protocol Refillable {
    func refill()
}

protocol Vehicle: Drivable, Refillable {
    var numberOfWheels: Int { get }
}
```

Let's add a new parameter to the `@Mockable` macro in order to know at the file level the other protocols who inherit from it.
This takes the shape of a variadic list of protocol
```swift
@Mockable(inheritedBy: ProtocolA, ProtocolB ...)
```

Taking back to our example it would look like this
```swift
// ---------- Vehicle.swift ---------
@Mockable
protocol Vehicle: Drivable, Refillable {
    var numberOfWheels: Int { get }
}

// Macro expansion remains unchanged
final class MockVehicle: Vehicle { ... }
```
```swift
// ---------- Refilable.swift ---------
@Mockable(inheritedBy: Vehicle) // <- new
protocol Refillable {
    func refill()
}

// Macro expansion adds a new conformance in an extension
final class MockRefillable: Refillable { ... }

extension MockVehicle: Refillable { ... } // <- adds an extension for each type declared in the "inheritedBy" section with the protocol requirements
```
```swift
// ---------- Drivable.swift ---------
@Mockable(inheritedBy: Vehicle) // <- new
protocol Drivable {
    func drive()
}

// Macro expansion adds a new conformance in an extension
final class MockDrivable: Drivable { ... }

extension MockVehicle: Drivable { ... } // <- same as Refillable

```
This is possible because Swift allows declaring protocol conformance at the type declaration and implementing it in an extension.

We could include a docstring specifying that in the case of inherited protocols, conformance to the sub-protocol must be declared at the file level with `@Mockable(inheritedBy:<NAME OF THE PROTOCOL>)`

+ Pros:
It works 🎉

- Cons:
It requires to write the name of the inherited protocols at the parent protocol level which may feel a bit counterintuitive

**Comment by Kolos65** [comment]
@ArseneSoulie Thanks for the issue!

I love this idea, but unfortunately a macro can only generate extensions for the type it was attached to.:
> [The generated extensions of the macro must only extend the type the macro is attached to.](https://github.com/swiftlang/swift-evolution/blob/main/proposals/0402-extension-macros.md)

So the `@Mockable` macro on `Refillable` is not allowed to generate an extension of `MockVehicle`.

**Comment by Kolos65** [comment]
I have thought about this limitation a lot and would rather go for the direction of mock implementation classes inheriting from the parent protocol's mock implementation class. 

This would require serious changes to the core implementation of the library, but I will give it a try shortly.

**Comment by ArseneSoulie** [comment]
> [The generated extensions of the macro must only extend the type the macro is attached to.](https://github.com/swiftlang/swift-evolution/blob/main/proposals/0402-extension-macros.md)

Wow I did not know about that, thanks for the info !

> mock implementation classes inheriting from the parent protocol's mock implementation class

That's another thing that I thought about but how would you go around to do it since multiple class inheritance is not supported ?

**Comment by Kolos65** [comment]
Good catch! I think lifting this limitation for single inheritances would be a big win already.

**Comment by ArseneSoulie** [comment]
I've thought up of another idea using delegates. It could solve our multiple inheritance problem without needing to change the way we use the macro by keeping the simple `@Mockable`. 
Tell me if this could work in your opinion (there might be some more macro limitations that I don't know of)

```swift
@Mockable
protocol Drivable {
    func drive()
}

// Macro expansion
final class MockDrivable: Drivable { // <- implementation as usual
    func drive() {}
}

// we'll use a delegate to use the implementation of other classes
protocol DelegatableDrivable: AnyObject {
    var delegateDrivable: Drivable { get }
}

// Here we call the implementation of the delegate
extension Drivable where Self: DelegatableDrivable {
    func drive() {
        delegateDrivable.drive()
    }
}
```

Same thing for refillable
```swift
@Mockable
protocol Refillable {
    func refill()
}

// Macro expansion
final class MockRefillable: Refillable {
    func refill() {}
}

protocol DelegatableRefillable: AnyObject {
    var delegateRefillable: Refillable { get }
}

extension Refillable where Self: DelegatableRefillable {
    func refill() {
        delegateRefillable.refill()
    }
}
```
```swift
@Mockable
protocol Vehicle: Drivable, Refillable {
    var numberOfWheels: Int { get }
}

//Macro expansion
final class MockVehicle: Drivable, Refillable, DelegatableDrivable, DelegatableRefillable, Vehicle {
    var numberOfWheels { } // <- implementation as usual

    var delegateRefillable: Refillable = MockRefillable()
    var delegateDrivable: Drivable = MockDrivable()
}

// + same thing as the other w/ delegate etc.

let mockVehicle = MockVehicle()
// here we have now access to all the implementation methods without ever having to know them in the file
mockVehicle.numberOfWheels
mockVehicle.refill()
mockVehicle.driver()
```

**Comment by Kolos65** [comment]
This seems like a good workaround.

Not sure if the `where Self: DelegatableRefillable ` constraint is allowed in generated extensions, I need to check this. 

This would in theory solve the conformance to parent protocols, but a challenge that still makes this seem impossible (same with the class inheritance idea) is that we still can't generate the member symbols of parent protocols (ex: `refill()`) inside the builder struct declarations without having this information at the time of macro expansion.

Without this you won't be able to write:

```swift
verify(mockVehicle)
     .refill().called(.atLeastOnce)
```

**Comment by ArseneSoulie** [comment]
That's right, I thought about it after having the last idea in the hopes that a solution exists 😅
I'll try some experiments with macros to see what's possible and what's not

**Comment by ArseneSoulie** [comment]
I couldn't manage to find a fix/workaround and came to the same conclusion as you.
- Reflection only works at runtime
- Delegates lack the total context at the child level
- [`lexicalContext`](https://forums.swift.org/t/macros-accessing-the-parent-context-of-a-syntax-node-passed-to-a-macro/64443/25) in macros only give the lexical context of the parent scope in the same syntax tree and will not explore parent/related trees
- Extensions are disallowed because of their sheer power 🔥 
- Macros cannot be partially built to have access to the access to the generated fields

It was a fun exploration, I'll let you choose the faith of this issue and close it or keep it.

**Comment by Kolos65** [comment]
@ArseneSoulie Thanks for your contribution to this discussion, I am closing this for now.
