### ISSUE TITLE
Add a way to call completion function from perform

### ISSUE THREAD

**Issue by swwol** [Kolos65/Mockable#69]
I'm looking at migrating from SwiftyMocky to Mockable. 

One feature that seems to be missing and is blocking me from being able to do this is the ability to call the completion closure of a function from perform

eg SwiftyMocky allows this:

```
// Perform allows to execute given closure, with all the method parameters, as soon as it is being called
Perform(mock, .methodThatTakesCompletionBlock(completion: .any, perform: { completion in
    completion(true,nil)
}))
```

I can't see any way to do the equivalent in Mockable at the moment.

**Comment by Kolos65** [comment]
You can do this with willProduce using a given clause.

**Comment by swwol** [comment]
> You can do this with willProduce using a given clause.

Thanks - will try that!
