### ISSUE TITLE
willProduce loses @escaping annotation on closures

### ISSUE THREAD

**Issue by swwol** [Kolos65/Mockable#70]
In some of the tests I am converting to use Mockable, the completion handler is stored in a local variable. This is not working as the willProduce producer does not mark the closure as @escaping, meaning it cannot be assiigned to a local variable.

example:

```
 let loyaltyProfileService = MockLoyaltyProfileService()
    var capturedCompletion: ((Result<LoyaltyProfile, Error>) -> Void)?
    given(loyaltyProfileService)
      .fetchLoyaltyProfile(completion: .any)
      .willProduce { completion in
        capturedCompletion = completion
      }
```

This results in an error: Assigning non-escaping parameter 'completion' to an @escaping closure

**Comment by Kolos65** [comment]
Thanks for the issue @swwol!

I prepared a PR to fix this in #71, will merge it shortly.
