### ISSUE TITLE
Support custom names for Mocked types

### ISSUE THREAD

**Issue by abrahamduran** [Kolos65/Mockable#72]
I think it would be a nice addition to allow devs to pass a custom name for their mocked types.

Something like this:

```swift
@Mockable(name: "MockAwesomeService")
protocol MyAwesomeSuperServiceInterface {
    ...
}
```

**Comment by Kolos65** [comment]
Hey @abrahamduran, thanks for the issue and PR! 

Can you describe the use case for this feature? When and why do you need control over the name of the mock implementation?

Also, this would allow users to easily break the `@attached(peer, names: prefixed(Mock))` symbol generation rule which I think would introduce ambiguity when using the this feature.

**Comment by Kolos65** [comment]
@abrahamduran I just checked your implementation and indeed using a custom name for the generated mock will not compile:
```swift
@Mockable(name: "Something")
protocol Foo {
    func foo()
}
#if MOCKING
final class Something: Foo, MockableService { // Declaration name 'Something' is not covered by macro 'Mockable'
```

Attached peer macros are not allowed to produce arbitrary names so the generated mock implementation must have a name that follows a name generation rule.

Im closing this issue as this cannot be implemented.

Thanks for contributing the idea regardless 🎉
