### ISSUE TITLE
Support for Swift Testing

### ISSUE THREAD

**Issue by xmanu** [Kolos65/Mockable#79]
It would be nice, if Mockable would (somehow) add support for Swift Testing in `verify`.

Right now verify is implemented by passing XCTAssert in. This has the issue that when Swift Testing is used that potential assertion errors while verifying are not reported at all. We missed some issues after migrating because of this.

Right now I circumvent this by introducing my own `verifyTesting` method that instead uses `Issue.record`.

```
public func verifyTesting<T: MockableService>(_ service: T) -> T.VerifyBuilder {
    service.verify { assertion, message, filePath, line in
        if !assertion() {
            let msg = message()
            Issue.record(
                .init(rawValue: msg),
                sourceLocation: .init(fileID: #fileID, filePath: "\(filePath)", line: Int(line), column: 0)
            )
        }
    }
}
```

This approach is just barely working so far, but is far from correct (we pass the wrong `#fileId` and `column` for example...)

I don't know how this would be best incorporated into the library (probably by passing around a full `sourceLocation` captured at the correct spot or also capturing `#fileID` and `#column`)... Also it is not clear to me how to provide a concise way of picking the right version of verify for the right test library...

Let me know if I can be of any help with this...

**Comment by xmanu** [comment]
Maybe `fatalError` would be a Testing library agnostic possibility? It is already used in the Mocker and might work here aswell...

**Comment by Kolos65** [comment]
Im strongly considering adding pointfree's [swift-issue-reporting](https://github.com/pointfreeco/swift-issue-reporting) as a dependency. It would resolve to the appropriate test failure and as a bonus would eliminate the need for the additional MockableTest target.

**Comment by Kolos65** [comment]
You're right, we need to extend the library to capture #fileID, #filePath and #column as well.
