### ISSUE TITLE
Use class inheritance to support protocol refinement

### ISSUE THREAD

**Issue by nathansalaun-sofia** [Kolos65/Mockable#83]
Protocol refinement is currently not supported by the macro since the macro cannot "see" the refined protocol.

Could this be achieved by making the generated mock of the refinement _inherit_ the generated mock of the refined protocol?

For example, the following code doesn't work:

```swift
protocol A {
    func a()
}

@Mockable
protocol B: A {
    func b()
}
```

Because the generated `MockB` doesn't have `func a()`. 

However, if we were to do this:

```swift
@Mockable
protocol A {
    func a()
}

@Mockable(refining: MockA.self)
protocol B: A {
    func b()
}
```

Then the generated code for `MockB` could be :

```swift
class MockB: MockA, ModelActionsApplier, MockableService {
    // ...
}
```

This way, `MockB` would allow mocking both `A` and `B` transparently.

**Comment by Kolos65** [comment]
@nathansalaun-sofia 
Thanks for the issue! I have explored this idea earlier and decided against it as:
- This would only solve single inheritance as multi class inheritance is not allowed.
- While implementing the class inheritance part of the macro would be fairly easy, this approach would also require the complete re-write of the whole library as the internal enums that represent protocol members cannot inherit from the parent's member representations. A new kind of member representation would need to be created which the child mocks can inherit. Im not even sure this is possible and I concluded it's not worth it for only solving part of the inheritance-problem.
