### ISSUE TITLE
Failed to build when enabled upcoming feature `ExistentialAny`

### ISSUE THREAD

**Issue by vvisionnn** [Kolos65/Mockable#90]
Hi @Kolos65 thanks for build such a great project and helped us a lot
while we are trying to upgrade to the latest version of Mockable but there is a build error says
```
Use of protocol 'Error' as a type must be written 'any Error'
```

this should be caused by the project settings
```swift
.enableUpcomingFeature("ExistentialAny")
```

well I know this is an upcoming feature and not enabled by default in swift 6 language mode
but this feature is added start from swift 5.6 and some of open source repos like `ComposableArchitecture` have already enabled it, we are preparing for the migration of swift 6 so enabled it as well

here is a tiny repro project for help identify this error
[MockableRepro.zip](https://github.com/user-attachments/files/18075985/MockableRepro.zip)

**Comment by Kolos65** [comment]
Thanks for the issue @vvisionnn prepared a fix in #91

**Comment by Kolos65** [comment]
@vvisionnn Released fix in `0.1.2`

**Comment by vvisionnn** [comment]
Thanks @Kolos65 !

**Comment by Kolos65** [comment]
Sorry, I missed adding the feature flag to the test targets so this did not came out.

**Comment by Kolos65** [comment]
I added the macro fix, can you confirm using the [fix-any-existential](https://github.com/Kolos65/Mockable/tree/fix-any-existential) branch?

**Comment by vvisionnn** [comment]
sure let me try with the fix branch

**Comment by vvisionnn** [comment]
@Kolos65 it is fixed now, and compile without error
<img width="2501" alt="image" src="https://github.com/user-attachments/assets/f8a2ad36-eb8f-4e7c-ac75-add9b4eddb76">

**Comment by Kolos65** [comment]
Thanks for verifying, created a new release again with this
