### ISSUE TITLE
Request: Remove Combine Dependency

### ISSUE THREAD

**Issue by Tyler-Keith-Thompson** [Kolos65/Mockable#93]
This library is soooo close to being able to work on Linux and provide easy mocking in the Swift on Server ecosystem. Unfortunately, it's utilizing Combine which is not available on Linux. 

Can you remove the Combine dependency and support Linux?

If you require a current value subject that's linux and async/await compatible, might I suggest an [implementation similar to this one](https://github.com/Tyler-Keith-Thompson/Afluent/blob/main/Sources/Afluent/CurrentValueSubject.swift)?

**Comment by Kolos65** [comment]
Started work on this in #94

**Comment by Kolos65** [comment]
@Tyler-Keith-Thompson You were right as the CI job passed on linux for the first run after removing Combine 🚀

**Comment by Kolos65** [comment]
@Tyler-Keith-Thompson Linux support was added in Mockable `0.2.0`

**Comment by Tyler-Keith-Thompson** [comment]
Fantastic! Thank you!
